### ISSUE TITLE
Unreadable hint

### ISSUE THREAD

**Issue by pmetx** [Gimly/vscode-matlab#20] opened 2017-09-21 01:54 UTC
![image](https://user-images.githubusercontent.com/32150577/30675312-578ff53e-9eb2-11e7-93a5-2da0ec50f566.png)

I have installed a Chinese version MATLAB, and the hint is in Chinese in MATLAB. But the hint given by vscode-matlab is not readable.

**Comment by amauragis** [comment] 2017-09-21 15:02
Duplicate of #16

**Comment by Gimly** [comment] 2017-09-21 15:10
As @amauragis said, it is a duplicate of #16. Closing this issue to have only one place to discuss this problem. @pmtex feel free to go there too add information if you want.

**Closed by Gimly** 2017-09-21 15:10 UTC
