### ISSUE TITLE
Highlighting issue when using nested comments

### ISSUE THREAD

**Issue by AnnyCaroline** [Gimly/vscode-matlab#69] opened 2019-01-26 20:13 UTC
Hi, 

![image](https://user-images.githubusercontent.com/17753656/51792271-e659cf80-2195-11e9-9b50-3ec94214dec2.png)

The highlight of nested comments does not seem to work correctly

**Comment by SheldonZhong** [comment] 2019-03-05 15:12
This issue is repetitive of #31.

**Comment by AnnyCaroline** [comment] 2019-03-29 02:33
It doesn't seem to be a repetitive issue.

**Comment by Gimly** [comment] 2019-03-29 07:43
@AnnyCaroline You're right, the issue isn't exactly the same. @rlivings39 has opened an issue for the official grammar, I'll include the fix as soon as they have fixed the issue on their side.

**Comment by Gimly** [comment] 2019-04-14 15:12
Version 1.1.0 should fix this issue which was fixed on Mathwork's official grammar.

**Closed by Gimly** 2019-04-14 15:12 UTC
Labels: bug, waiting for external
