### ISSUE TITLE
Lint messages display on .md files, which is not needed

### ISSUE THREAD

**Issue by psychelzh** [Gimly/vscode-matlab#24] opened 2017-10-22 07:48 UTC
I have a `.md` file to display directory information. But lint messages will also display on this file. 

![lint_noneed](https://user-images.githubusercontent.com/13306020/31859577-7059a5fa-b740-11e7-8105-260c94873e7b.png)

**Comment by sco1** [comment] 2017-10-27 16:13
What do you have for `files.associations` in your user settings?

**Comment by Gimly** [comment] 2017-10-27 20:38
I did several tests, and can't reproduce your issue. As @sco1 said, could you check your files associations? Could you maybe give a screenshot of the whole VSCode window with the .md file open?

**Comment by psychelzh** [comment] 2017-10-28 02:20
It did occur 6 days occur, but I cannot reproduce it now. I will feedback if it occured again.

**Comment by Gimly** [comment] 2017-10-28 07:25
Ok, closing the issue for now, please update with more information when you can reproduce and I'll reopen. Thanks!

**Closed by Gimly** 2017-10-28 07:25 UTC

**Comment by psychelzh** [comment] 2019-04-20 06:49
Now lint message display on `.gitignore`, `.json`, `.sh` files, too. If I open one of these files for a long time in vscode, the message will always appears!
