### ISSUE TITLE
2.2.0 freezing VS code on large files

### ISSUE THREAD

**Issue by RobinTournemenne** [Gimly/vscode-matlab#142] opened 2021-10-07 09:40 UTC
Hi Gimly,

sorry to tell you that this interesting 2.2.0 update seems to freeze VS Code on a large matlab file (during colorization I guess): 689 lines defining one structure containing notably large cell arrays (~20 cells usually) with matrix inside (usually 2x20).

I cannot provide you with this confidential file, but maybe if you really need it, I can create an identical fac simile.

Best regards,

Robin

PS: I switched back to 2.0.1 which scans files 10 times faster

**Comment by SNDST00M** [comment] 2021-10-20 13:49
That tokenizeLine2 function could actually be `vscode-textmate` being called from the VSC Textmate language service.

Perhaps this would all work better if that service had access to token data from the vscode API itself

**Comment by SNDST00M** [comment] 2021-10-21 12:06
Work is underway. Fix will land in `vscode-textmate-language@0.1.1` on 28/10.

**Comment by SNDST00M** [comment] 2021-11-20 14:20
As with #140, I was adding a test suite in the backend TM-based service and that's now done. This will be fixed soon™

**Comment by SNDST00M** [comment] 2021-12-01 23:10
Had some regressions, sorry for the delay. I'll be making QOL changes for package devs then will try publish tomorrow.

**Closed** 2021-12-13 12:33 UTC
Labels: bug

**Comment by SNDST00M** [comment] 2021-12-14 09:33
Please give us an update on this issue - it seems to have improved but not vanished entirely for me

**Comment by RobinTournemenne** [comment] 2021-12-15 09:47
Nice to see that it goes forward!

Does the file that I shared above works for you? (PARAMETRES_BUG2.m)

On my fairly decent machine:
- arrows do not respond anymore,
- save takes 3 seconds,
- VS code can freeze randomly for quite some time,
- Closing VS Code takes 10 seconds.
(- it takes still a longer time to load, but that's a detail compared to the points above)

Still not useable even if VS Code does not completely freeze anymore.

**Comment by RobinTournemenne** [comment] 2021-12-15 09:54
"Go to definition" is also lagging but unfortunately also in "normal" situations. See the attached example that I made. It is a fac simile. When I try to go to youpi.m (via alt+click for axample or F12) it takes few seconds (it is instantaneous in version 2.0.1). In the original file (which is longer) it takes up to 30 seconds...

[script.zip](https://github.com/Gimly/vscode-matlab/files/7718185/script.zip)

**Comment by SNDST00M** [comment] 2021-12-15 10:21
Save takes 2 seconds for me, Go To Definiton as well. But the `COUCOU` function combined with the `extractorMidiarpege1` logic actually times out when I <kbd>alt</kbd>-<kbd>LMB</kbd> `youpi()`.

I think it would be beneficial to create a new tracking issue and also note there that Mathworks is working on a vastly more performant LSP ~~that they keep teasing in the Discord goddamnit~~

**Comment by RobinTournemenne** [comment] 2021-12-15 10:40
+1 

And also for Go to definition. It took 2 seconds on the file that I created but on a file with more lines it will increase to an even more undesireable number of seconds ^^

I revert to 2.0.1 waiting for better days.

**Comment by Gimly** [comment] 2021-12-15 12:51
@SNDST00M unfortunately looks like the issue isn't only for big files given the new issues that we are getting about slowness.

**Comment by SNDST00M** [comment] 2021-12-15 12:56
I decided to have the engine hash files with SHA1 so that they weren't being compared by a table index of the entire document. I suspect this caused the slowdown but I'll run some tests to see if it's significantly faster without.

**Comment by SNDST00M** [comment] 2021-12-15 14:41
Okay thanks to #152 and @fschwaiger we've isolated the issue to Textmate scope parsers and it'll be a tougher nut to crack. I hope I break ground on this one by the weekend and it remains feasible to keep the Atom parsers

**Comment by SNDST00M** [comment] 2022-03-18 23:26
As I understand it, this is still outstanding along with #162. But we await perf testing after #157.
Note potential workaround - https://github.com/Gimly/vscode-matlab/issues/157#issuecomment-1030228546 - in the meantime.

**Comment by M00TSDNS** [comment] 2023-01-28 00:29
Should be fixed by #174. This necessitated a full rewrite of the library:

- [`a767ee6d5ab1145685a527ed77730b431f367729`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/a767ee6d5ab1145685a527ed77730b431f367729)
- [`777883f8031cd8cde5644f2e9dc134926f1e984f`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/777883f8031cd8cde5644f2e9dc134926f1e984f)
- [`f387eb353dfd1afd990a329113833f605ab39cb7`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/f387eb353dfd1afd990a329113833f605ab39cb7)
- [`44f583f653c277b99631189ac536f6187b484fe0`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/44f583f653c277b99631189ac536f6187b484fe0)
- [`bd3d75d4dca0fe48b9612e9485befe797959c9d1`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/bd3d75d4dca0fe48b9612e9485befe797959c9d1)
- [`502c90b4db8a7b3883eb8d3d05afec3f7f1dceeb`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/502c90b4db8a7b3883eb8d3d05afec3f7f1dceeb)
- [`85dfa3dae418e33f9e76b0f7d1cbe9a7f33a31df`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/commit/85dfa3dae418e33f9e76b0f7d1cbe9a7f33a31df)

Looking back, I cobbled the earlier iterations together and threw in code that was synchronous when it should have been rewritten to be async.. the async keyword was a great gift in the rewrite. I've also learnt a lot in the time I was busy and that helped bring sanity by killing the technical debt. Sorry I couldn't do it before but very happy at my 100 or so commits to clean the library up.
